---
# tasks file for roles/dns

- name: copy named.conf
  copy: src=master-named.conf dest=/etc/named.conf owner=root group=named mode=0640

- name: copy zones
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=named mode=0660
  with_items:
    - { src: "named.dns.lab", dest: "/var/named/master/" }
    - { src: "named.client1-dns.lab", dest: "/var/named/master/" }
    - { src: "named.client2-dns.lab", dest: "/var/named/master/" }
    - { src: "named.dns.lab.rev", dest: "/var/named/master/" }
    - { src: "named.client1-dns.lab.rev", dest: "/var/named/master/" }
    - { src: "named.client2-dns.lab.rev", dest: "/var/named/master/" }
    - { src: "named.newdns.lab", dest: "/var/named/master/" }
    - { src: "named.ddns.lab", dest: "/var/named/dynamic/" }

- name: copy resolv.conf to the servers
  template: src=servers-resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644
  
- name: set /etc/named permissions
  file: path=/etc/named owner=root group=named mode=0670

- name: ensure named is running and enabled
  service: name=named state=restarted enabled=yes
